name: CI/CD on github
on:  [push, pull_request]
jobs:
  build-linux:
    name: build with ${{ matrix.compiler }}
    runs-on: ubuntu-latest
    strategy:
      matrix:
        compiler: [g++, clang++]
        include:
          - compiler: g++
            install: g++
          - compiler: clang++
            install: clang
    steps:
      - name: check code
        uses: actions/checkout@v4
      - name: Install compiler
        run: |
          sudo apt-get update
          sudo apt-get install -y cmake ${{ matrix.install }}
      - name: configure with CMake
        run: cmake -H. -B_build -DCMAKE_CXX_COMPILER=${{ matrix.compiler }}
      - name: build project
        run: cmake --build _build
      - name: run tests
        run: |
          cd _build
          ctest --output-on-failure
  build-windows:
    name: build with VS 
    runs-on: windows-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: configure with CMakeS
        run:  cmake -S . -B _build
      - name: build project
        run: cmake --build _build --config Release
      - name: run tests
        run: |
          cd _build
          ctest -C Release --output-on-failure
  coverage:
    - name: Code Coverage
      runs-on: ubuntu-latest
      steps:
        - uses: actions/checkout@v4

        - name: Install lcov
          run: sudo apt-get install -y lcov

        - name: configure
          run: cmake -S . -B _build -DCMAKE_BUILD_TYPE=Debug

        - name: buiild
          run: cmake --build _build

        - name: run tests
          run: cd _build && ctest --output-on-failure

        - name: generate coverage
          run: |
            lcov --capture --directory _build --output-file coverage.info
            lcov --remove coverage.info \
              `/usr/include/*` \
              `${{github.workspace}}/_build/_deps/*` \
              `${{github.workspace}}/tests/*` \
              --output-file coverage.info
        - name: upload
          uses: coverallsapp/github-action@v2
          with:
            github-token: ${{secrets.GITHUB_TOKEN}}
            file: coverage.info
            format: lcov